env:
    node: true
    browser: true
    mocha: true
    es6: true
extends: 'eslint:recommended'
rules:
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
